### ISSUE TITLE
ObjectDiffer throws exception when simultaneously calling the compare(working, base) method from multiple threads.

### ISSUE THREAD

**Issue by whdupreez** [SQiShER/java-object-diff#148] opened 2015-12-11 14:25 UTC
First off, thanks for a great library!

We are experiencing some issues when sharing the ObjectDiffer between multiple threads.

The user guide indicates that the ObjectDiffer is thread safe: "The ObjectDiffer is created by the ObjectDifferBuilder. It takes two objects to compare and eventually returns a DiffNode representing the entire object graph. It is thread-safe and can be reused."

Using a single instance of the ObjectDiffer in a high concurrency environment with multiple threads calling the below snippet of code simultaneously, we get the IllegalArgumentException below: 

```
	ObjectDiffer differ = ObjectDifferBuilder.buildDefault();
	private String patchToText(R working, R base) {
		DiffNode node = this.differ.compare(working, base);
		...
```

```
java.lang.IllegalArgumentException: Detected inconsistency in enter/leave sequence. Must always be LIFO.
	at de.danielbechler.diff.circular.CircularReferenceDetector.remove(CircularReferenceDetector.java:113) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.forgetInstances(DifferDispatcher.java:205) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:164) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:145) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:93) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingIntrospection(BeanDiffer.java:114) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingAppropriateMethod(BeanDiffer.java:104) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compare(BeanDiffer.java:80) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:188) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:158) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:145) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:93) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingIntrospection(BeanDiffer.java:114) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingAppropriateMethod(BeanDiffer.java:104) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compare(BeanDiffer.java:80) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:188) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:158) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:145) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:93) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.CollectionDiffer.compareItems(CollectionDiffer.java:119) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.CollectionDiffer.compare(CollectionDiffer.java:75) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:188) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:158) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:145) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:93) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingIntrospection(BeanDiffer.java:114) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingAppropriateMethod(BeanDiffer.java:104) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compare(BeanDiffer.java:80) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:188) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:158) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:145) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:93) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingIntrospection(BeanDiffer.java:114) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingAppropriateMethod(BeanDiffer.java:104) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compare(BeanDiffer.java:80) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:188) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:158) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:145) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:93) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingIntrospection(BeanDiffer.java:114) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compareUsingAppropriateMethod(BeanDiffer.java:104) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.BeanDiffer.compare(BeanDiffer.java:90) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:188) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:158) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:145) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:93) ~[java-object-diff-0.93.jar:?]
	at de.danielbechler.diff.ObjectDiffer.compare(ObjectDiffer.java:49) ~[java-object-diff-0.93.jar:?]
```

Changing the method to create a new ObjectDiffer with every method invocation fixes the issue:

```
	private String patchToText(R working, R base) {
		ObjectDiffer differ = ObjectDifferBuilder.buildDefault();
		DiffNode node = this.differ.compare(working, base);
		...
```

When running the below test, the following NullPointerException gets thrown:

```
	@Test
	public void test_concurrent() throws Exception {
		ExecutorService executor = Executors.newFixedThreadPool(10);
		ObjectDiffer differ = ObjectDifferBuilder.buildDefault();
		for (int idx = 0; idx < 1_000_000; idx++) {
			executor.submit(new Runnable() {
				@Override
				public void run() {
					try {
						OuterObject working = new OuterObject();
						working.setValueA("");
						working.setValueB("");
						OuterObject base = new OuterObject();
						differ.compare(working, base);
						differ.compare(base, working);
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			});
		}
		Thread.sleep(10_000);
	}
```

```
java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893)
	at de.danielbechler.diff.circular.CircularReferenceDetector.knows(CircularReferenceDetector.java:62)
	at de.danielbechler.diff.circular.CircularReferenceDetector.push(CircularReferenceDetector.java:52)
	at de.danielbechler.diff.differ.DifferDispatcher.transactionalPushToCircularReferenceDetectors(DifferDispatcher.java:229)
	at de.danielbechler.diff.differ.DifferDispatcher.rememberInstances(DifferDispatcher.java:224)
	at de.danielbechler.diff.differ.DifferDispatcher.compareWithCircularReferenceTracking(DifferDispatcher.java:155)
	at de.danielbechler.diff.differ.DifferDispatcher.compare(DifferDispatcher.java:145)
	at de.danielbechler.diff.differ.DifferDispatcher.dispatch(DifferDispatcher.java:93)
	at de.danielbechler.diff.ObjectDiffer.compare(ObjectDiffer.java:49)
	at com.ngl.micro.business.store.DifferTest$1.run(DifferTest.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

When moving the creation of the differ into the run method so that a new differ gets created for every diff, then everything works as expected and no exceptions are thrown. At the moment we are working around the issue by creating a new differ every time we have to perform a diff. There appears to be no visible impact on performance, but we would prefer to have a single reusable instance of the ObjectDiffer.

We are running Java 8 and have experienced this issue on both Windows and Linux using a number of different JDK 8 update versions.

Thanks

**Comment by tacoo** [comment] 2016-01-22 14:57
I have same issue. I had to add 'synchronized' before compare method called.
```java
    public static void main(String[] args) throws Exception {
        Object lock = new Object();
        ObjectDiffer differ = ObjectDifferBuilder.buildDefault();
        ExecutorService executorService = Executors.newFixedThreadPool(10);
        List<Callable<Boolean>> tasks = IntStream.range(0, 100).mapToObj(i -> {
            Callable<Boolean> callable = new Callable<Boolean>() {
                @Override
                public Boolean call() throws Exception {
                    Map<String, String> m1 = new HashMap<>();
                    m1.put("a", "1");
                    Map<String, String> m2 = new HashMap<>();
                    m2.put("a", "b");
                    // synchronized (lock) {
                    return differ.compare(m1, m2).hasChanges();
                    // }
                }
            };
            return callable;
        }).collect(Collectors.toList());

        List<Future<Boolean>> result = executorService.invokeAll(tasks);
        for (Future<Boolean> f : result) {
            try {
                Boolean hasChanges = f.get();
                if (!hasChanges) {
                    System.out.println("should have changes!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        executorService.shutdown();
    }
```

**Comment by SQiShER** [comment] 2016-01-22 15:05
Thanks for letting me know. I'm currently very short on time, but I'll try to take a look at it over the weekend.

**Comment by tacoo** [comment] 2016-01-22 17:54
The reason why cause this error is, CircularReferenceDetector on the dispatcher is not thread safe. I committed sample into my repo. Hope it helps.

**Comment by SQiShER** [comment] 2016-01-22 21:24
@tacoo The changes in your repo look pretty good. Would you like to open a pull request? There are some minor changes I'd like to suggest, but we can talk about those in the PR thread.

**Closed** 2016-01-24 14:28 UTC

**Comment by SQiShER** [comment] 2016-01-24 14:36
Thanks for the help, guys . I also added a modified version of @whdupreez example as regression test, to make sure the problem doesn't come back.

**Comment by tacoo** [comment] 2016-01-26 04:08
Thank you @SQiShER  :+1:

**Comment by tacoo** [comment] 2016-01-26 04:31
I just noticed that my changes cause memory leak when compare method throw exception.
So we need to do try-finally.

```
dispatcher.resetInstanceMemory();
try {
  DiffNode diffNode = dispatcher.dispatch(DiffNode.ROOT, Instances.of(working, base), RootAccessor.getInstance());
  return diffNode;
} finally {
  dispatcher.clearInstanceMemory();
}
```

**Comment by SQiShER** [comment] 2016-01-26 12:38
@tacoo Yup, good call. Wanna create another pull request for the fix? Otherwise I'll fix it tonight.

**Comment by Elhosni** [comment] 2021-08-24 12:21
@SQiShER, firstable thanks for a great library!
We somehow have memory leaks problem using your librarie. We are using the latest version. 
We noticed that @tacoo changes with circular references didnt fix the issue. 

![memory leak 1](https://user-images.githubusercontent.com/20160593/130615274-815473e0-d8b8-4a32-9bf7-fbf5f474e066.png)

![memory leak 2](https://user-images.githubusercontent.com/20160593/130615350-9fd2e10e-9558-473a-918e-71c76f06239a.png)
